"""Generate downloadable PDF reports from chat answers / content."""
import io
import re
from datetime import datetime, timezone
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from app import config


def _clean(t: str) -> str:
    t = t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    t = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", t)
    return t


def build_pdf(title: str, body: str, sources: list[dict] | None = None, author_email: str = "") -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm,
                            leftMargin=2 * cm, rightMargin=2 * cm, title=title)
    ss = getSampleStyleSheet()
    h = ParagraphStyle("H", parent=ss["Title"], fontSize=20, textColor=colors.HexColor("#0f766e"))
    meta = ParagraphStyle("M", parent=ss["Normal"], fontSize=9, textColor=colors.grey)
    body_st = ParagraphStyle("B", parent=ss["Normal"], fontSize=11, leading=16)
    src_st = ParagraphStyle("S", parent=ss["Normal"], fontSize=9, textColor=colors.HexColor("#555"), leading=13)

    flow = [Paragraph(_clean(title), h)]
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    flow.append(Paragraph(f"Generated by {config.PRODUCT_NAME} · {stamp}" + (f" · {author_email}" if author_email else ""), meta))
    flow.append(Spacer(1, 10))
    flow.append(HRFlowable(width="100%", color=colors.HexColor("#dddddd")))
    flow.append(Spacer(1, 12))
    for para in body.split("\n"):
        if para.strip():
            flow.append(Paragraph(_clean(para), body_st))
            flow.append(Spacer(1, 6))
    if sources:
        flow.append(Spacer(1, 14))
        flow.append(Paragraph("<b>Sources</b>", body_st))
        for s in sources:
            flow.append(Paragraph(f"[{s['n']}] {s['filename']} — {s['location']}", src_st))
    doc.build(flow)
    return buf.getvalue()
